language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

install:
    - mkdir -p build/log
    - travis_retry composer update --no-interaction

before_script: phpenv config-add config.ini
